---
title: "Introduction to the `pimeta` package"
author: "Kengo Nagashima"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Introduction to the `pimeta` package}
  %\VignetteEncoding{UTF-8}
---

The `pimeta` package is easy.
Load your data and then pass it the `pima` function!

```{r, echo = TRUE, fig.width = 5, fig.height = 3}
require("pimeta")
data(sbp, package = "pimeta")

# a parametric bootstrap prediction interval
set.seed(20161102)
out <- pima(
  y  = sbp$y,      # effect size estimates
  se = sbp$sigmak, # within studies standard errors
  B  = 5000        # some options (e.g., number of bootstrap samples)
)
out
plot(out, base_size = 10)
```

Several type of methods are supported.
```{r, echo = TRUE}
# Higgins-Thompson-Spiegelhalter prediction interval
pima(sbp$y, sbp$sigmak, method = "HTS")

# Partlett-Riley prediction interval (Hartung and Knapp's SE)
pima(sbp$y, sbp$sigmak, method = "HK")

# Partlett-Riley prediction interval (Sidik and Jonkman's SE)
pima(sbp$y, sbp$sigmak, method = "SJ")
```
