// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// pwchisqCpp
List pwchisqCpp(const double q, const Eigen::VectorXd& lambda, const Eigen::VectorXi& mult, const Eigen::VectorXd& delta, const int n, const double mode, const int maxit, const double eps);
RcppExport SEXP _pimeta_pwchisqCpp(SEXP qSEXP, SEXP lambdaSEXP, SEXP multSEXP, SEXP deltaSEXP, SEXP nSEXP, SEXP modeSEXP, SEXP maxitSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type q(qSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type mult(multSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(pwchisqCpp(q, lambda, mult, delta, n, mode, maxit, eps));
    return rcpp_result_gen;
END_RCPP
}
// bootPICppWrap
List bootPICppWrap(const Eigen::VectorXd& rnd, const Eigen::VectorXd& y, const Eigen::VectorXd& sigma, const double alpha);
RcppExport SEXP _pimeta_bootPICppWrap(SEXP rndSEXP, SEXP ySEXP, SEXP sigmaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type rnd(rndSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(bootPICppWrap(rnd, y, sigma, alpha));
    return rcpp_result_gen;
END_RCPP
}
// rtau2CppWrap
NumericVector rtau2CppWrap(const int n, const Eigen::VectorXd& y, const Eigen::VectorXd& sigma, const double mode, const int maxit1, const double eps, const double lower, const double upper, const int maxit2, const double tol, const int nthread);
RcppExport SEXP _pimeta_rtau2CppWrap(SEXP nSEXP, SEXP ySEXP, SEXP sigmaSEXP, SEXP modeSEXP, SEXP maxit1SEXP, SEXP epsSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP maxit2SEXP, SEXP tolSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit1(maxit1SEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< const double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit2(maxit2SEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(rtau2CppWrap(n, y, sigma, mode, maxit1, eps, lower, upper, maxit2, tol, nthread));
    return rcpp_result_gen;
END_RCPP
}
