# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dwchisqCpp <- function(q, lambda, mult, delta, n, mode, maxit, eps) {
    .Call(`_pimeta_dwchisqCpp`, q, lambda, mult, delta, n, mode, maxit, eps)
}

bootPICppWrap <- function(rnd, y, sigma, alpha) {
    .Call(`_pimeta_bootPICppWrap`, rnd, y, sigma, alpha)
}

rtau2CppWrap <- function(n, y, sigma, mode, maxit1, eps, lower, upper, maxit2, tol) {
    .Call(`_pimeta_rtau2CppWrap`, n, y, sigma, mode, maxit1, eps, lower, upper, maxit2, tol)
}

